name: Linux build

on: [push]

jobs:
  builds:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64
      - name: compile
        run: |
          ./gradlew clean jar
      - name: logfiles
        if: ${{ failure() }}
        shell: bash
        run: |
          echo "Logfiles: "
          ps || True
          ls vms/server_1/LoadbalancerTest-jpro/logs || True
          cat vms/server_1/LoadbalancerTest-jpro/logs/jpro.console.log  || True